[theme]
base = "light"
primaryColor = "#3B82F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#111827"
font = "sans serif"

[client]
toolbarMode = "viewer"
showErrorDetails = true

[browser]
gatherUsageStats = false